language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -U setuptools==`grep setuptools versions.cfg | awk '{print $3}'`
    - pip install zc.buildout==`grep '^zc.buildout' versions.cfg | awk '{print $3}'`
    - buildout bootstrap
    - buildout install test alltests
script:
    - bin/alltests -v
after_success:
    # Bails out for non-tags
    - ./update_index.sh
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
