# AppVeyor CI settings (Windows Machine CI Tests)

environment:
  WIN_COV: '  ' # some whitespaces to have a trueish value.
  matrix:
    - PROFILE: py37-conventions
      PYTHON_VERSION: 3.7"
      TOXENV: "lint-py37"
    - PROFILE: py37
      PYTHON_VERSION: 3.7"
      TOXENV: "py37,py37-deps"
    - PROFILE: py35
      PYTHON_VERSION: 3.5"
      TOXENV: "py35,py35-deps"
    - PROFILE: py36
      PYTHON_VERSION: 3.6"
      TOXENV: "py36,py36-deps"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "python.exe -m pip install tox"

build: off

max_jobs: 2

matrix:
  fast_finish: true

test_script:
  - "tox.exe"
