# AppVeyor CI settings (Windows Machine CI Tests)

environment:
  WIN_COV: '  ' # some whitespaces to have a trueish value.
  matrix:
    - TOXENV: py38
    - TOXENV: py37
    - TOXENV: py36

install:
  - pip install "setuptools < 52"
  - pip install tox

build: off

matrix:
  fast_finish: true

test_script:
  - tox
